export const projects = [
  {
    id: 'course-options',
    name: 'Course Options',
    role: 'Higher-education discovery platform for students and counsellors',
    body: [
      'Course Options is a higher-education discovery platform focused on helping students compare programmes, understand costs, and make better decisions with less friction. The experience blends programme discovery, filtering, guidance, and conversion support into one product journey.',
      'I worked on the product experience around discovery, search relevance, and decision support, with emphasis on trust, clarity, and performance at scale. The result was a product that felt easier to navigate while still giving users the depth they needed to evaluate options seriously.',
    ],
    stack: ['Next.js', 'TypeScript', 'Node.js', 'MongoDB', 'Redis', 'PWA'],
    link: { label: 'Open live product', href: 'https://courseoptions.com/' },
    images: [
      '/projects/course-options/course-ui-1.png',
      '/projects/course-options/course-ui-2.png',
      '/projects/course-options/course-ui-3.png',
      '/projects/course-options/course-ui-4.png',
      '/projects/course-options/course-ui-5.png',
    ],
    panel: {
      label: 'project focus',
      meta: 'student decision flow',
      rows: [
        { key: 'search', value: 'relevance', score: '0.96', bar: 0.96 },
        { key: 'compare', value: 'programme fit', score: '0.91', bar: 0.91 },
        { key: 'workflow', value: 'counsellor tools', score: '0.88', bar: 0.88 },
        { key: 'ux', value: 'clearer journey', score: '0.83', bar: 0.83 },
      ],
      note: 'The product goal was to reduce uncertainty in course discovery and make programme comparison feel easier, faster, and more trustworthy.',
    },
  },
  {
    id: 'enterprise-lms',
    name: 'Enterprise LMS',
    role: 'Learning platform with delivery, assessments, and reporting workflows',
    body: [
      'This project was designed for an enterprise training environment where reliability and teaching workflows mattered as much as UI polish. It covered course delivery, assessments, enrolment flows, and reporting for a large learner audience.',
      'I contributed to the frontend and product architecture around course detail, admin operations, and reporting. The focus was to make the system easier to manage and more dependable for high-traffic learning periods.',
    ],
    stack: ['React', 'Next.js', 'TypeScript', 'Apollo GraphQL', 'Redux', 'Tailwind'],
    link: { label: 'Confidential implementation · visual overview shown', href: null },
    images: [
      '/projects/lms-admin/lms-course.png',
      '/projects/lms-admin/lms-programs.png',
      '/projects/lms-admin/lms-topics.png',
      '/projects/lms-admin/lms-subjects.png',
      '/projects/lms-admin/lms-quiz.png',
      '/projects/lms-admin/lms-create-quiz.png',
      '/projects/lms-admin/lms-payment-plan.png',
    ],
    panel: {
      label: 'admin workflow',
      meta: 'course operations',
      rows: [
        { key: 'content', value: 'course setup', score: '0.92', bar: 0.92 },
        { key: 'assessment', value: 'quiz logic', score: '0.89', bar: 0.89 },
        { key: 'payments', value: 'plans + billing', score: '0.86', bar: 0.86 },
        { key: 'scale', value: 'multi-module admin', score: '0.84', bar: 0.84 },
      ],
      note: 'This project focused on operational clarity: course structure, assessments, payment flows, and admin workflows that had to be consistent and easy to manage.',
    },
  },
  {
    id: 'connectify',
    name: 'Connectify',
    role: 'Multi-role event management platform for organisers and attendees',
    body: [
      'Connectify is a full-stack event platform with separate Admin, Organizer, and Attendee experiences. It covers event creation, attendee discovery, booking, notifications, profiles, and role-based access.',
      'I worked across the full-stack architecture and route design, including the organizer creation flow, attendee booking journey, and notification behaviour. Seeded demo accounts and future-dated events make the platform easy to evaluate as a realistic product flow.',
    ],
    stack: ['React', 'Create React App', 'Redux', 'Node.js', 'Express', 'MongoDB', 'JWT', 'File uploads'],
    link: { label: 'Open live demo', href: 'https://connectify-gold-one.vercel.app/' },
    images: [
      '/projects/connectify/screenshot-1.png',
      '/projects/connectify/screenshot-2.png',
      '/projects/connectify/screenshot-3.png',
      '/projects/connectify/screenshot-4.png',
    ],
    panel: {
      label: 'event lifecycle',
      meta: '3 user roles',
      rows: [
        { key: 'creation', value: 'organizer flow', score: '0.91', bar: 0.91 },
        { key: 'booking', value: 'attendee journey', score: '0.89', bar: 0.89 },
        { key: 'access', value: 'protected routes', score: '0.92', bar: 0.92 },
        { key: 'updates', value: 'notifications', score: '0.84', bar: 0.84 },
      ],
      note: 'The project demonstrates how shared event data can support distinct admin, organizer, and attendee workflows without mixing their responsibilities.',
    },
  },
  {
    id: 'erp-teacher-portal',
    name: 'ERP Teacher Portal',
    role: 'Academic operations SPA for timetable, student records, and teacher workflows',
    body: [
      'This role-aware academic ERP front-end simulates the daily workflows a teacher needs: timetable, nominal roll, student records, profile management, leave and loan actions, and internal notifications.',
      'I designed the core teacher screens, route structure, data-dense tables, forms, and filters. The frontend uses structured mock data so the experience can be evaluated independently while remaining ready for backend integration.',
    ],
    stack: ['React', 'TypeScript', 'Vite', 'Redux Toolkit', 'React Router', 'Tailwind CSS'],
    link: { label: 'Open live demo', href: 'https://erp-teacher-portal-five.vercel.app/' },
    images: [
      '/projects/erp-teacher-portal/screenshot-1.png',
      '/projects/erp-teacher-portal/screenshot-2.png',
      '/projects/erp-teacher-portal/screenshot-3.png',
      '/projects/erp-teacher-portal/screenshot-4.png',
      '/projects/erp-teacher-portal/screenshot-5.png',
      '/projects/erp-teacher-portal/screenshot-6.png',
      '/projects/erp-teacher-portal/screenshot-7.png',
      '/projects/erp-teacher-portal/screenshot-8.png',
      '/projects/erp-teacher-portal/screenshot-9.png',
      '/projects/erp-teacher-portal/screenshot-10.png',
    ],
    panel: {
      label: 'academic operations',
      meta: 'teacher workflow SPA',
      rows: [
        { key: 'navigation', value: 'role-aware routes', score: '0.92', bar: 0.92 },
        { key: 'records', value: 'student tables', score: '0.90', bar: 0.9 },
        { key: 'planning', value: 'timetable flow', score: '0.87', bar: 0.87 },
        { key: 'forms', value: 'leave + profile', score: '0.85', bar: 0.85 },
      ],
      note: 'The focus was turning institutional tasks into reusable screens with clear navigation, dense but readable data, and consistent state handling.',
    },
  },
  {
    id: 'online-tutor',
    name: 'Online Tutor',
    role: 'Role-based education platform for admins, teachers, and students',
    body: [
      'This platform brought together multiple education roles in one system so admins, teachers, and students each had a workflow that fit their responsibilities. It included course management, messaging, enrolment flows, and content-driven learning operations.',
      'I built the role-specific interfaces and the modular architecture behind them. The goal was to keep the system organised and scalable while still making each user journey feel clear and focused.',
    ],
    stack: ['React', 'TypeScript', 'Vite', 'Next.js', 'Redux Toolkit', 'Tailwind'],
    link: { label: 'Confidential implementation · visual overview shown', href: null },
    images: [
      '/projects/online-tutor/online-home.png',
      '/projects/online-tutor/online-about.png',
      '/projects/online-tutor/online-blog.png',
      '/projects/online-tutor/online-blog-detail.png',
      '/projects/online-tutor/online-subjects.png',
      '/projects/online-tutor/online-tutor-detail.png',
      '/projects/online-tutor/online-register.png',
      '/projects/online-tutor/online-register-1.png',
      '/projects/online-tutor/online-register-2.png',
    ],
    panel: {
      label: 'multi-role operations',
      meta: 'admin + tutor + student',
      rows: [
        { key: 'enrolments', value: 'role flow', score: '0.92', bar: 0.92 },
        { key: 'messaging', value: 'student touchpoints', score: '0.86', bar: 0.86 },
        { key: 'access', value: 'role-based gates', score: '0.89', bar: 0.89 },
        { key: 'content', value: 'learning modules', score: '0.83', bar: 0.83 },
      ],
      note: 'The project focused on role-specific user journeys and keeping educational workflows clear across admin, tutor, and student actions.',
    },
  },
  {
    id: 'carsinstant',
    name: 'CarsInstant',
    role: 'Automotive marketplace for inventory discovery, financing, and lead generation',
    body: [
      'CarsInstant is a conversion-focused car marketplace built around verified dealer flows, transparent pricing, and inventory exploration by body type, brand, and budget.',
      'I worked on inventory discovery, filter-driven browsing, trust-signal sections, testimonials, and financing pathway UX. The product combines marketplace browsing with structured lead-generation touchpoints so users can move from exploration to enquiry with less friction.',
    ],
    stack: ['React', 'Next.js', 'TypeScript', 'Redux Toolkit', 'Tailwind CSS'],
    link: { label: 'Open live product', href: 'https://www.carsinstant.com' },
    images: [
      '/projects/carsinstant/cars-first.png',
      '/projects/carsinstant/screenshot-1.png',
      '/projects/carsinstant/screenshot-2.png',
      '/projects/carsinstant/screenshot-3.png',
      '/projects/carsinstant/screenshot-4.png',
      '/projects/carsinstant/screenshot-5.png',
      '/projects/carsinstant/screenshot-6.png',
    ],
    panel: {
      label: 'marketplace discovery',
      meta: 'browse to enquiry',
      rows: [
        { key: 'inventory', value: 'filtered browsing', score: '0.92', bar: 0.92 },
        { key: 'trust', value: 'dealer signals', score: '0.88', bar: 0.88 },
        { key: 'financing', value: 'guided pathway', score: '0.85', bar: 0.85 },
        { key: 'conversion', value: 'lead touchpoints', score: '0.90', bar: 0.9 },
      ],
      note: 'The product work connected practical vehicle search with trust signals and clear next steps for buyers and dealers.',
    },
  },
  {
    id: 'responica',
    name: 'Responica',
    role: 'Digital agency and BPO platform focused on service discovery and lead capture',
    body: [
      'Responica is a service-led corporate platform for a digital solutions and BPO business covering web, mobile, marketing, telesales, and quality assurance services.',
      'I delivered end-to-end service pages and conversion-focused sections, including testimonials, FAQs, and contact funnel modules. The goal was to make a broad service offering credible, scannable, and easy for prospective clients to act on.',
    ],
    stack: ['React', 'Vite', 'TypeScript', 'Tailwind CSS'],
    link: { label: 'Open live product', href: 'https://responica.vercel.app/' },
    images: [
      '/projects/responica/screenshot-1.png',
      '/projects/responica/screenshot-2.png',
      '/projects/responica/screenshot-3.png',
      '/projects/responica/screenshot-4.png',
      '/projects/responica/screenshot-5.png',
      '/projects/responica/screenshot-6.png',
    ],
    panel: {
      label: 'service conversion',
      meta: 'content to enquiry',
      rows: [
        { key: 'services', value: 'clear offering', score: '0.91', bar: 0.91 },
        { key: 'credibility', value: 'proof sections', score: '0.87', bar: 0.87 },
        { key: 'answers', value: 'FAQ structure', score: '0.84', bar: 0.84 },
        { key: 'contact', value: 'lead funnel', score: '0.89', bar: 0.89 },
      ],
      note: 'The challenge was balancing credibility content with direct conversion paths across several service categories.',
    },
  },
  {
    id: 'rechnungslens',
    name: 'RechnungsLens',
    role: 'Explainable invoice review and validation platform for German invoice workflows',
    body: [
      'RechnungsLens is a document-intelligence project focused on incoming invoices in the German market. The workflow is built around upload, extraction, validation, and a clear Release / Review / Reject decision model for AP teams handling PDF, scan, photo, and structured XML inputs.',
      'The app uses a fast path for ZUGFeRD and XRechnung files, then falls back to Gemini-based extraction for scans and plain PDFs, followed by deterministic validation for missing fields, VAT format checks, and arithmetic verification. It is designed to explain the decision rather than hide it behind a black box.',
    ],
    stack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Google Gemini', 'PDF/XML processing', 'Validation engine'],
    link: { label: 'Open live demo', href: 'https://rechnungs-lens-tawny.vercel.app/' },
    images: [
      '/projects/rechnungslens/home.png',
      '/projects/rechnungslens/results-release.png',
      '/projects/rechnungslens/roadmap.png',
      '/projects/rechnungslens/rechnungslens-live.png',
    ],
    panel: {
      label: 'explainable pipeline',
      meta: 'upload to decision',
      rows: [
        { key: 'input', value: 'PDF + XML', score: '0.95', bar: 0.95 },
        { key: 'extraction', value: 'confidence', score: '0.90', bar: 0.9 },
        { key: 'validation', value: 'deterministic', score: '0.94', bar: 0.94 },
        { key: 'decision', value: 'release / review', score: '0.92', bar: 0.92 },
      ],
      note: 'The project makes invoice processing explainable: structured files use a direct XML path, while extracted fields are checked before a clear decision is shown.',
    },
  },
  {
    id: 'pos-system',
    name: 'SK100 Frontend',
    role: 'Operations dashboard for inventory, invoices, purchases, and sales control',
    body: [
      'SK100 Frontend is an operations dashboard built around the day-to-day workflows of a small business: sales, stock, purchases, invoices, suppliers, expenses, and receipts.',
      'I focused on making dense operational screens readable and consistent. The value of the project is in its workflow structure: users can move between records, review totals, and complete routine tasks without losing context.',
    ],
    stack: ['JavaScript', 'HTML5', 'CSS3', 'REST APIs', 'Business UI'],
    link: { label: 'Confidential implementation · visual overview shown', href: null },
    images: [
      '/projects/pos-system/pos-dashboard.png',
      '/projects/pos-system/pos-sales.png',
      '/projects/pos-system/pos-inventory.png',
      '/projects/pos-system/pos-purchases.png',
      '/projects/pos-system/pos-invoices.png',
      '/projects/pos-system/pos-expenses.png',
      '/projects/pos-system/pos-receipts.png',
      '/projects/pos-system/pos-suppliers.png',
    ],
    panel: {
      label: 'business operations',
      meta: 'daily workflow coverage',
      rows: [
        { key: 'sales', value: 'POS + receipts', score: '0.92', bar: 0.92 },
        { key: 'stock', value: 'inventory control', score: '0.90', bar: 0.9 },
        { key: 'finance', value: 'invoices + expenses', score: '0.88', bar: 0.88 },
        { key: 'records', value: 'suppliers + purchases', score: '0.86', bar: 0.86 },
      ],
      note: 'The interface is organised around the business tasks users repeat most: selling, checking stock, recording purchases, and reviewing financial records.',
    },
  },
]

export const skills = [
  {
    group: 'Frontend',
    items: ['React', 'Next.js', 'TypeScript', 'JavaScript', 'Redux Toolkit', 'Tailwind CSS', 'HTML5', 'CSS3'],
  },
  {
    group: 'Backend',
    items: ['Node.js', 'Express.js', 'REST APIs', 'GraphQL', 'JWT/OAuth', 'Stripe', 'WebSockets'],
  },
  {
    group: 'Data & Systems',
    items: ['MongoDB', 'MySQL', 'PostgreSQL', 'Redis', 'Docker', 'Git', 'CI/CD', 'SQL'],
  },
  {
    group: 'Product',
    items: ['Product thinking', 'Requirements translation', 'Performance tuning', 'Agile delivery', 'Code review', 'Cross-functional work'],
  },
]
