export const projects = [
  {
    id: 'course-options',
    name: 'Course Options',
    role: 'Higher-education discovery platform for students and counsellors',
    body: [
      'Course Options helps students compare programmes, scholarships, and costs before they commit to an application. It brings search, SmartMatch, financial planning, UCAS support, and counsellor assistance into one journey.',
      'I built discovery and filtering modules, connected notifications and social auth, and worked on Redis-backed search and admin content governance. My aim was simple: give students enough context to make a serious decision without making them fight the interface.',
    ],
    stack: ['Next.js', 'TypeScript', 'Node.js', 'MongoDB', 'Redis', 'PWA'],
    link: { label: 'Open live product', href: 'https://courseoptions.com/' },
    images: [
      '/projects/course-options/course-ui-1.png',
      '/projects/course-options/course-ui-2.png',
      '/projects/course-options/course-ui-3.png',
      '/projects/course-options/course-ui-4.png',
      '/projects/course-options/course-ui-5.png',
    ],
    panel: {
      label: 'project focus',
      meta: 'student decision flow',
      rows: [
        { key: 'search', value: 'relevance', score: '0.96', bar: 0.96 },
        { key: 'compare', value: 'programme fit', score: '0.91', bar: 0.91 },
        { key: 'workflow', value: 'counsellor tools', score: '0.88', bar: 0.88 },
        { key: 'ux', value: 'clearer journey', score: '0.83', bar: 0.83 },
      ],
      note: 'I treated search, comparison, and counsellor handoff as one connected journey rather than separate screens.',
    },
  },
  {
    id: 'enterprise-lms',
    name: 'Enterprise LMS',
    role: 'Learning platform with delivery, assessments, and reporting workflows',
    body: [
      'This LMS handled course delivery, HLS video, live lectures, assessments, payment plans, coupons, and reporting for a large training operation.',
      'I worked on enrolment and payment flows, course detail pages, the admin and student portals, quiz modules, topic trees, and reporting dashboards. The hard part was keeping everyday admin work predictable while the system handled peak exam traffic.',
    ],
    stack: ['React', 'Next.js', 'TypeScript', 'Apollo GraphQL', 'Redux', 'Tailwind'],
    link: { label: 'Confidential implementation · visual overview shown', href: null },
    images: [
      '/projects/lms-admin/lms-course.png',
      '/projects/lms-admin/lms-programs.png',
      '/projects/lms-admin/lms-topics.png',
      '/projects/lms-admin/lms-subjects.png',
      '/projects/lms-admin/lms-quiz.png',
      '/projects/lms-admin/lms-create-quiz.png',
      '/projects/lms-admin/lms-payment-plan.png',
    ],
    panel: {
      label: 'admin workflow',
      meta: 'course operations',
      rows: [
        { key: 'content', value: 'course setup', score: '0.92', bar: 0.92 },
        { key: 'assessment', value: 'quiz logic', score: '0.89', bar: 0.89 },
        { key: 'payments', value: 'plans + billing', score: '0.86', bar: 0.86 },
        { key: 'scale', value: 'multi-module admin', score: '0.84', bar: 0.84 },
      ],
      note: 'The useful part of this work was making course, assessment, and payment operations feel like one dependable system.',
    },
  },
  {
    id: 'connectify',
    name: 'Connectify',
    role: 'Multi-role event management platform for organisers and attendees',
    body: [
      'Connectify gives admins, organizers, and attendees different ways to work with the same event data. Organizers create events, attendees discover and book them, and admins keep the system in order.',
      'I worked on the full-stack route design, organizer creation flow, booking journey, notifications, and seeded demo data. The project taught me to be strict about permissions because every role sees a different version of the same event lifecycle.',
    ],
    stack: ['React', 'Create React App', 'Redux', 'Node.js', 'Express', 'MongoDB', 'JWT', 'File uploads'],
    link: { label: 'Open live demo', href: 'https://connectify-gold-one.vercel.app/' },
    images: [
      '/projects/connectify/screenshot-1.png',
      '/projects/connectify/screenshot-2.png',
      '/projects/connectify/screenshot-3.png',
      '/projects/connectify/screenshot-4.png',
    ],
    panel: {
      label: 'event lifecycle',
      meta: '3 user roles',
      rows: [
        { key: 'creation', value: 'organizer flow', score: '0.91', bar: 0.91 },
        { key: 'booking', value: 'attendee journey', score: '0.89', bar: 0.89 },
        { key: 'access', value: 'protected routes', score: '0.92', bar: 0.92 },
        { key: 'updates', value: 'notifications', score: '0.84', bar: 0.84 },
      ],
      note: 'The important boundary here is ownership: organizers manage events, attendees manage bookings, and admins manage the system around them.',
    },
  },
  {
    id: 'erp-teacher-portal',
    name: 'ERP Teacher Portal',
    role: 'Academic operations SPA for timetable, student records, and teacher workflows',
    body: [
      'This teacher portal puts timetable, nominal roll, student records, profile management, leave and loan requests, and internal notifications in one working view of the school day.',
      'I designed the teacher screens, route structure, tables, forms, and filters. It runs on structured mock data, so the workflows can be reviewed now and connected to a backend later without redesigning the interface.',
    ],
    stack: ['React', 'TypeScript', 'Vite', 'Redux Toolkit', 'React Router', 'Tailwind CSS'],
    link: { label: 'Open live demo', href: 'https://erp-teacher-portal-five.vercel.app/' },
    images: [
      '/projects/erp-teacher-portal/screenshot-1.png',
      '/projects/erp-teacher-portal/screenshot-2.png',
      '/projects/erp-teacher-portal/screenshot-3.png',
      '/projects/erp-teacher-portal/screenshot-4.png',
      '/projects/erp-teacher-portal/screenshot-5.png',
      '/projects/erp-teacher-portal/screenshot-6.png',
      '/projects/erp-teacher-portal/screenshot-7.png',
      '/projects/erp-teacher-portal/screenshot-8.png',
      '/projects/erp-teacher-portal/screenshot-9.png',
      '/projects/erp-teacher-portal/screenshot-10.png',
    ],
    panel: {
      label: 'academic operations',
      meta: 'teacher workflow SPA',
      rows: [
        { key: 'navigation', value: 'role-aware routes', score: '0.92', bar: 0.92 },
        { key: 'records', value: 'student tables', score: '0.90', bar: 0.9 },
        { key: 'planning', value: 'timetable flow', score: '0.87', bar: 0.87 },
        { key: 'forms', value: 'leave + profile', score: '0.85', bar: 0.85 },
      ],
      note: 'I designed around the tasks a teacher repeats, with dense information kept readable and close at hand.',
    },
  },
  {
    id: 'online-tutor',
    name: 'Online Tutor',
    role: 'Role-based education platform for admins, teachers, and students',
    body: [
      'Online Tutor separates the work of admins, teachers, and students without splitting the product into disconnected experiences. It covers enrolment, lectures, messaging, payments, profiles, blogs, FAQs, and testimonials.',
      'I built role-specific dashboards, lecture and enrolment flows, messaging, payment workflows, route guards, and the public marketing pages. The main architectural decision was to keep shared patterns reusable while letting each role stay focused.',
    ],
    stack: ['React', 'TypeScript', 'Vite', 'Next.js', 'Redux Toolkit', 'Tailwind'],
    link: { label: 'Confidential implementation · visual overview shown', href: null },
    images: [
      '/projects/online-tutor/online-home.png',
      '/projects/online-tutor/online-about.png',
      '/projects/online-tutor/online-blog.png',
      '/projects/online-tutor/online-blog-detail.png',
      '/projects/online-tutor/online-subjects.png',
      '/projects/online-tutor/online-tutor-detail.png',
      '/projects/online-tutor/online-register.png',
      '/projects/online-tutor/online-register-1.png',
      '/projects/online-tutor/online-register-2.png',
    ],
    panel: {
      label: 'multi-role operations',
      meta: 'admin + tutor + student',
      rows: [
        { key: 'enrolments', value: 'role flow', score: '0.92', bar: 0.92 },
        { key: 'messaging', value: 'student touchpoints', score: '0.86', bar: 0.86 },
        { key: 'access', value: 'role-based gates', score: '0.89', bar: 0.89 },
        { key: 'content', value: 'learning modules', score: '0.83', bar: 0.83 },
      ],
      note: 'The same system supports three audiences, but each audience gets only the actions and information it needs.',
    },
  },
  {
    id: 'carsinstant',
    name: 'CarsInstant',
    role: 'Automotive marketplace for inventory discovery, financing, and lead generation',
    body: [
      'CarsInstant helps people browse vehicles by body type, brand, and budget, then move from a shortlist to a dealer enquiry. Verified dealer information and transparent pricing do a lot of the trust-building work.',
      'I built inventory discovery, filter-driven browsing, trust sections, testimonials, and the financing pathway. I paid particular attention to the point where browsing becomes an enquiry, because that is where a marketplace either helps or loses the user.',
    ],
    stack: ['React', 'Next.js', 'TypeScript', 'Redux Toolkit', 'Tailwind CSS'],
    link: { label: 'Open live product', href: 'https://www.carsinstant.com' },
    images: [
      '/projects/carsinstant/cars-first.png',
      '/projects/carsinstant/screenshot-1.png',
      '/projects/carsinstant/screenshot-2.png',
      '/projects/carsinstant/screenshot-3.png',
      '/projects/carsinstant/screenshot-4.png',
      '/projects/carsinstant/screenshot-5.png',
      '/projects/carsinstant/screenshot-6.png',
    ],
    panel: {
      label: 'marketplace discovery',
      meta: 'browse to enquiry',
      rows: [
        { key: 'inventory', value: 'filtered browsing', score: '0.92', bar: 0.92 },
        { key: 'trust', value: 'dealer signals', score: '0.88', bar: 0.88 },
        { key: 'financing', value: 'guided pathway', score: '0.85', bar: 0.85 },
        { key: 'conversion', value: 'lead touchpoints', score: '0.90', bar: 0.9 },
      ],
      note: 'The interface connects browsing with a clear next step instead of leaving the buyer at the end of a listing page.',
    },
  },
  {
    id: 'responica',
    name: 'Responica',
    role: 'Digital agency and BPO platform focused on service discovery and lead capture',
    body: [
      'Responica presents a digital solutions and BPO business across web, mobile, marketing, telesales, and QA services. The site has to explain a broad offer without making visitors work to understand it.',
      'I delivered the service pages, testimonials, FAQs, and contact funnel. I used a clear content structure so credibility comes before the enquiry prompt, rather than turning every section into a sales pitch.',
    ],
    stack: ['React', 'Vite', 'TypeScript', 'Tailwind CSS'],
    link: { label: 'Open live product', href: 'https://responica.vercel.app/' },
    images: [
      '/projects/responica/screenshot-1.png',
      '/projects/responica/screenshot-2.png',
      '/projects/responica/screenshot-3.png',
      '/projects/responica/screenshot-4.png',
      '/projects/responica/screenshot-5.png',
      '/projects/responica/screenshot-6.png',
    ],
    panel: {
      label: 'service conversion',
      meta: 'content to enquiry',
      rows: [
        { key: 'services', value: 'clear offering', score: '0.91', bar: 0.91 },
        { key: 'credibility', value: 'proof sections', score: '0.87', bar: 0.87 },
        { key: 'answers', value: 'FAQ structure', score: '0.84', bar: 0.84 },
        { key: 'contact', value: 'lead funnel', score: '0.89', bar: 0.89 },
      ],
      note: 'The copy and layout give visitors enough evidence to trust the service before asking them to make contact.',
    },
  },
  {
    id: 'rechnungslens',
    name: 'RechnungsLens',
    role: 'Explainable invoice review and validation platform for German invoice workflows',
    body: [
      'RechnungsLens is a German invoice intake tool. A user uploads a PDF, scan, photo, or structured e-invoice and gets an explainable Release, Review, or Reject decision.',
      'ZUGFeRD and XRechnung files take a direct XML path. Plain PDFs and scans use Gemini extraction, then deterministic checks cover required fields, VAT format, totals, and purchase-order warnings. The point is to show why a decision was made.',
    ],
    stack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Google Gemini', 'PDF/XML processing', 'Validation engine'],
    link: { label: 'Open live demo', href: 'https://rechnungs-lens-tawny.vercel.app/' },
    images: [
      '/projects/rechnungslens/home.png',
      '/projects/rechnungslens/results-release.png',
      '/projects/rechnungslens/roadmap.png',
      '/projects/rechnungslens/rechnungslens-live.png',
    ],
    panel: {
      label: 'explainable pipeline',
      meta: 'upload to decision',
      rows: [
        { key: 'input', value: 'PDF + XML', score: '0.95', bar: 0.95 },
        { key: 'extraction', value: 'confidence', score: '0.90', bar: 0.9 },
        { key: 'validation', value: 'deterministic', score: '0.94', bar: 0.94 },
        { key: 'decision', value: 'release / review', score: '0.92', bar: 0.92 },
      ],
      note: 'Each decision has a reason: parse what is structured, extract what is not, then validate both with the same rules.',
    },
  },
  {
    id: 'pos-system',
    name: 'SK100 Frontend',
    role: 'Operations dashboard for inventory, invoices, purchases, and sales control',
    body: [
      'SK100 is a lightweight operations dashboard for sales, stock, purchases, invoices, suppliers, expenses, VAT reporting, and receipts.',
      'I built the API integration patterns, pagination-heavy lists, and the handoffs between inventory, sales, and reporting. It is intentionally practical: users should be able to finish a routine task without losing their place.',
    ],
    stack: ['JavaScript', 'HTML5', 'CSS3', 'REST APIs', 'Business UI'],
    link: { label: 'Confidential implementation · visual overview shown', href: null },
    images: [
      '/projects/pos-system/pos-dashboard.png',
      '/projects/pos-system/pos-sales.png',
      '/projects/pos-system/pos-inventory.png',
      '/projects/pos-system/pos-purchases.png',
      '/projects/pos-system/pos-invoices.png',
      '/projects/pos-system/pos-expenses.png',
      '/projects/pos-system/pos-receipts.png',
      '/projects/pos-system/pos-suppliers.png',
    ],
    panel: {
      label: 'business operations',
      meta: 'daily workflow coverage',
      rows: [
        { key: 'sales', value: 'POS + receipts', score: '0.92', bar: 0.92 },
        { key: 'stock', value: 'inventory control', score: '0.90', bar: 0.9 },
        { key: 'finance', value: 'invoices + expenses', score: '0.88', bar: 0.88 },
        { key: 'records', value: 'suppliers + purchases', score: '0.86', bar: 0.86 },
      ],
      note: 'The screens follow the order of real work: sell something, update stock, record the purchase, and review the numbers.',
    },
  },
]

export const skills = [
  {
    group: 'Frontend',
    items: ['React', 'Next.js', 'TypeScript', 'JavaScript', 'Redux Toolkit', 'Tailwind CSS', 'HTML5', 'CSS3'],
  },
  {
    group: 'Backend',
    items: ['Node.js', 'Express.js', 'REST APIs', 'GraphQL', 'JWT/OAuth', 'Stripe', 'WebSockets'],
  },
  {
    group: 'Data & Systems',
    items: ['MongoDB', 'MySQL', 'PostgreSQL', 'Redis', 'Docker', 'Git', 'CI/CD', 'SQL'],
  },
  {
    group: 'Product',
    items: ['Product thinking', 'Requirements translation', 'Performance tuning', 'Agile delivery', 'Code review', 'Cross-functional work'],
  },
]
